name: insightmind_app
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.0.3
  google_fonts: ^6.3.2
  smooth_page_indicator: ^1.2.1
  salomon_bottom_bar: ^3.3.2
  collection: ^1.17.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  uuid: ^4.5.2
  percent_indicator: ^4.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.11

flutter:
  uses-material-design: true

  assets:
    - assets/image/banner_health.png
    - assets/image/banner_mental_health.png
    - assets/image/empty_state.png
    - assets/image/empty.png
    - assets/image/empty_box.png
    - assets/image/mindset.png
